### ISSUE TITLE
Shadow in Android using setElevation

### ISSUE THREAD

**Issue by aboganas** [triniwiz/nativescript-popup#2]
I have tried to add shadow to Android part by using setElevation() which should provide shadowing for the Popwindow if the background is set and API >=21, but sill have no luck with that. 
when I tried 

`this._popup.setElevation(10);`

it says that setElevation is not a property, and when I try to do it to the view

`view.android.setElevation(10);`

nothing happens

**Comment by shiv19** [comment]
You'll have to set the background to a drawable before you can use set elevation

**Comment by aboganas** [comment]
ok I tried with 
`this._popup.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(new Color(this._options.backgroundColor).android)); `

now it works; however, I still get the following error
`../node_modules/nativescript-popup/popup.android.ts(104,21): error TS2339: Property 'setElevation' does not exist on type 'PopupWindow'.
`
even-though it works

**Comment by shiv19** [comment]
that's strange. not sure why

**Comment by triniwiz** [comment]
@aboganas it should be fixed for you now :)
